script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix test && git push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.9.1
otp_release: 22.0.7
services:
  - postgresql
before_script:
  - PGPASSWORD=postgres psql -c 'create database cat_and_wolf_test;' -U postgres
